FROM nginx:1.16.0-alpine
COPY ./frontend/src/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/ssl/* /etc/ssl/
COPY ./nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]