version: "3.7"

services:
  customerdriven-frontend:
    container_name: customerdriven-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3013:80'
    environment:
      - VIRTUAL_HOST=customerdriven.sanderkk.com
      - VIRTUAL_PORT=3013
      - LETSENCRYPT_HOST=customerdriven.sanderkk.com
      - LETSENCRYPT_EMAIL=sander.k.kilen@gmail.com
      - BACKEND_HOST=customerdriven-backend
    networks:
      - proxy
      - app
  customerdriven-backend:
    container_name: customerdriven-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend.prod
    volumes:
      - '.:/app'
    ports:
      - '3014:80'
      environment:
        - VIRTUAL_HOST=api-customerdriven.sanderkk.com
        - VIRTUAL_PORT=3014
        - LETSENCRYPT_HOST=api-customerdriven.sanderkk.com
        - LETSENCRYPT_EMAIL=sander.k.kilen@gmail.com
networks:
  - proxy
  - app
  networks:
    proxy:
      external:
        name: nginx-proxy
    app: