
pipeline {
    agent none

    environment {
        HOME = '.'
    }

    stages {
        stage('Backend build debug') {
            agent any
            steps {
                dir('./backend') {
                    sh 'dotnet restore'
                    sh 'sudo dotnet build'
                }
            }
        }
        // Build backend
        stage('Build backend') {
            agent any
            steps {
                dir('./backend/src') {
                    sh 'dotnet restore'
                    sh 'dotnet publish -c Release'
                }
            }
        }
        stage('Backend xunit tests') {
            agent any
            steps {
                dir('./backend') {
                    sh returnStdout:true, script:'sudo dotnet test'
                }
            }
        }
        // Install and build frontend
        stage('Build frontend') {
            agent {
                docker {
                    image 'node:lts'
                }
            }
            steps{
                dir('./frontend/src') {
                    sh 'node --version'
                    sh 'npm --version'
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        // Deploy frontend and backend
        stage('Deploy') {
            agent any
            steps {
                sh 'docker-compose up -d --build'
            }
        }
        stage('Save docker images as tar') {
            agent any
            steps {
                sh 'docker save -o /home/sanderkk/backend.tar customerdrivencd_customerdriven-backend'
                sh 'docker save -o /home/sanderkk/frontend.tar customerdrivencd_customerdriven-frontend'
            }
        }
        stage('Transfer docker images to azure server'){
            agent any
            steps {
                // Use scp for file transfer
                sh 'scp ./backend.tar FishFarmAdmin@137.116.234.188:/home/FishFarmAdmin/build'
                sh 'scp ./frontend.tar FishFarmAdmin@137.116.234.188:/home/FishFarmAdmin/build'
            }
        }
        stage('End to end tests') {
            agent any
            steps{
                dir('./frontend/tests') {
                    sh 'docker run -v $PWD/:/e2e -w /e2e -e false cypress/included:3.2.0'
                }
            }
        }
    }
}