export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";

export const SET_QUERY_DATA = "SET_QUERY_DATA";
export const SET_QUERY_DATA_INPUT = "SET_QUERY_DATA_INPUT";
export const SET_QUERY_DATA_RESPONSE = "SET_QUERY_DATA_RESPONSE";
export const REMOVE_QUERY_DATA = "REMOVE_QUERY_DATA";
