export const AAD_LOGIN_SUCCESS = "AAD_LOGIN_SUCCESS";
export const AAD_LOGOUT_SUCCESS = "AAD_LOGOUT_SUCCESS";

export const AAD_ACQUIRED_ACCESS_TOKEN_SUCCESS = "AAD_ACQUIRED_ACCESS_TOKEN_SUCCESS";

export const SET_QUERY_DATA = "SET_QUERY_DATA";
export const SET_QUERY_DATA_INPUT = "SET_QUERY_DATA_INPUT";
export const SET_QUERY_DATA_RESPONSE = "SET_QUERY_DATA_RESPONSE";
export const REMOVE_QUERY_DATA = "REMOVE_QUERY_DATA";

export const UPDATE_DASHBOARD_CELL = "UPDATE_DASHBOARD_CELL";
export const UPDATE_DASHBOARD = "UPDATE_DASHBOARD"
